---
# tasks file for mariadb

# - name: Install mariadb-server
#   ansible.builtin.package:
#     name: mariadb-server
#     state: present

# - name: Install galera
#   ansible.builtin.package:
#     name: galera
    # state: present

- name: config
  template:
    src: my.cnf
    dest: /etc/mysql/conf.d/galera.cnf
