---
# tasks file for glusterfs

- ansible.builtin.shell: grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '"'
  register: DEBID

- ansible.builtin.shell: grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+'
  register: DEBVER

- ansible.builtin.shell: dpkg --print-architecture
  register: DEBARCH

- name: Add repositories key
  ansible.builtin.apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/{{ gluster_version }}/rsa.pub
    state: present

- name: Add repositories
  ansible.builtin.apt_repository:
    repo: 'deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ DEBID["stdout"] }}/{{ DEBARCH["stdout"]  }}/apt {{ DEBVER["stdout"]  }} main'
    state: present
    filename: 'glusterfs'

- name: Install - glusterfs-server
  ansible.builtin.apt:
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - glusterfs-server

- name: Enable service glusterd
  ansible.builtin.systemd:
    name: glusterd.service
    enabled: true
    state: started

- name: Install - dep
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
    pkg:
      - parted

- name: Prep disk
  ansible.builtin.include_tasks: disk.yaml
  with_items:
    - vdb
    - vdc

- name: Test peers
  shell: gluster pool list | grep -i connected | wc -l
  register: output

- name: add pool
  when: "item != hosts[0] and output.stdout| int == 1"
  shell: "gluster peer probe {{ item  }}"
  with_items: "{{ hosts }}"
  delegate_to: "{{hosts[0]}}"
  run_once: true


- name: check exist
  shell: gluster volume list | grep {{ name_vol }}
  ignore_errors: true
  register: output
  delegate_to: "{{hosts[0]}}"
  run_once: true

- debug: var=output
  delegate_to: "{{hosts[0]}}"
  run_once: true

- name: Create replica
  when: output["rc"] != 0
  shell: gluster volume create {{ name_vol }} replica 3 node01:/gfs/brick_vdb/brick node02:/gfs/brick_vdb/brick node03:/gfs/brick_vdb/brick node01:/gfs/brick_vdc/brick node02:/gfs/brick_vdc/brick node03:/gfs/brick_vdc/brick
  register: output
  delegate_to: "{{hosts[0]}}"
  run_once: true
- debug: var=output
  delegate_to: "{{hosts[0]}}"
  run_once: true

- name: start replica
  shell:  gluster volume start {{ name_vol }}
  delegate_to: "{{hosts[0]}}"
  run_once: true

- name: Python Execution
  mg_disk: yourName=test
  register: result
- debug: var=result
