# apiVersion: node.k8s.io/v1
# kind: RuntimeClass
# metadata:
#   name: gvisor
# handler: runsc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <h1>LB works !!!</h1>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  volumes:
  - name: nginx-index
    configMap:
      name: nginx-index
  containers:
  - name: nginx
    image: nginx:stable
    volumeMounts:
      - name: nginx-index
        mountPath: "/usr/share/nginx/html/index.html"
        subPath: "index.html"
        readOnly: true
    ports:
      - containerPort: 80
        name: http-web-svc


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  - name: name-of-service-port2
    protocol: TCP
    port: 443
    targetPort: http-web-svc
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service3
# spec:
#   selector:
#     app.kubernetes.io/name: proxy
#   type: LoadBalancer
#   ports:
#   - name: name-of-service-port
#     protocol: TCP
#     port: 443
#     targetPort: http-web-svc
