apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor
handler: runsc
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  runtimeClassName: gvisor
  containers:
  - name: nginxw
    image: nginx:stable

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 443
    targetPort: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service3
spec:
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 443
    targetPort: http-web-svc
