- name: ACME test
  hosts: all
  gather_facts: false
  tasks:
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: /srv/account.key

    - name: Generate an OpenSSL Certificate Signing Request
      community.crypto.openssl_csr:
        path: /srv/account.csr
        privatekey_path: /srv/account.key
        common_name: www.autok8s.xyz

    - name: Create a challenge for sample.com using a account key file.
      community.crypto.acme_certificate:
        account_key_src: /srv/account.key
        csr: /srv/account.csr
        dest: /srv/sample.com.crt
        fullchain_dest: /srv/sample.com-fullchain.crt
        acme_directory: http://10.17.3.1:8050/acme/directory
        acme_version: 2
        account_email: test@autok8s.xyz
      register: acme_response

    - name: Debug ACME response
      debug:
        msg: "{{ acme_response }}"

    - name: Let the challenge(s) be validated and retrieve the cert and intermediate certificate
      community.crypto.acme_certificate:
        account_key_src: /srv/account.key
        csr: /srv/account.csr
        dest: /srv/sample.com.crt
        data: "{{ acme_response }}"
        acme_directory: http://10.17.3.1:8050/acme/directory
        account_email: test@autok8s.xyz
        acme_version: 2
        terms_agreed: true
