---
# vars file for swift
def_soft_Debian:
      - curl
      - gcc
      - memcached
      - rsync
      - sqlite3
      - xfsprogs
      - git-core
      - libffi-dev
      - python-setuptools 
      - liberasurecode-dev
      - libssl-dev
      - python-coverage 
      - python-dev 
      - python-nose
      - python-xattr
      - python-eventlet
      - python-greenlet
      - python-pastedeploy
      - python-netifaces
      - python-pip
      - python-dnspython
      - python-mock