---

- name: Template a file to calico.yml
  ansible.builtin.copy:
    src: calico.yml
    dest: /etc/kubernetes/config/calico.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Template dns.yml
  ansible.builtin.template:
    src: dns.yml
    dest: /etc/kubernetes/config/dns.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy file metrics-server components.yaml
  ansible.builtin.copy:
    src: components.yaml
    dest: /etc/kubernetes/config/components.yaml
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Kubectl apply
  ansible.builtin.command: "kubectl apply -f {{ item }}"
  ignore_errors: true
  run_once: true
  loop:
    - /etc/kubernetes/config/calico.yml
    - /etc/kubernetes/config/dns.yml
    - /etc/kubernetes/config/components.yaml

- name: Watch is all running
  ansible.builtin.shell: kubectl get pods -n kube-system -o=jsonpath="{ range .items[*] }{.status.phase}{'\n'}{end} " | grep -v -E '^$'  | grep -i -v running -c
  register: result
  until: result.stdout == '1'
  retries: 20
  delay: 10
