---
- name: Roles for haproxy/lb servers
  hosts: dns
  gather_facts: false
  roles:
    - autok8s.general.bind
    # - autok8s.general.keepalive
    # - autok8s.general.haproxy
  tags: [DNS]

- name: Roles for all servers
  hosts: all
  gather_facts: true
  roles:
    - autok8s.general.common
    - autok8s.general.firewall
  tags: [ALL]

- name: Roles routing
  hosts: bgp
  gather_facts: false
  roles:
    - autok8s.general.bird
  tags: [BGP]

- name: Install lbexternal
  hosts: lbexternal
  gather_facts: false
  roles:
    - autok8s.general.docker
    - autok8s.general.lbexternal
  tags: [LB]

# - name: Roles for CA servers
#   hosts: controlplane
#   gather_facts: false
#   roles:
#     - autok8s.general.ca
#   tags: [CA]
