---

- name: Roles for nodeK8S servers
  hosts: nodeK8S
  gather_facts: false
  roles:
    - autok8s.general.crt
    - autok8s.k8s.containerd
    - autok8s.k8s.kubelet
    - autok8s.k8s.kube_proxy
    - autok8s.k8s.calico
  tags: [nodeK8S]

- name: Roles for controlplane servers
  hosts: controlplane
  gather_facts: false
  roles:
    - autok8s.k8s.etcd_pod
    - autok8s.k8s.kube_apiserver_pod
    - autok8s.k8s.kube_scheduler_pod
    - autok8s.k8s.kube_controller_manager_pod
    - autok8s.k8s.cloud_controller_manager_pod
  tags: [CP]

- name: Prep cluster
  hosts: controlplane
  gather_facts: false
  roles:
    - autok8s.k8s.cluster
  tags: [CLUSTER]

- name: Install lbexternal
  hosts: lbexternal
  gather_facts: false
  roles:
    - autok8s.general.docker
    - autok8s.general.lbexternal
  tags: [LBE]
